[env:esp32dev]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM5
monitor_port = COM5
monitor_filters = esp32_exception_decoder
upload_flags = 
    --before=default_reset
    --after=hard_reset